### ISSUE TITLE
Discuss generic values

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-hamt-ipld#16]
Until very recently, the values stored by this code were `[]byte`s. I needed things to be more generic, so I changed it to be `interface{}`. This 'works', but it definitely suboptimal, especially due to how difficult it is to reason about marshaling of the value types. Currently, in my usecase for this, i'm using a 'deep copy pump' from refmt to convert the unmarshalled object from a `map[string]interface{}` thing to its actual type. This is ugly, and a hack.

*takes a breath*

It would actually be nice if go had generics.

There, I said it. Now let's move on.

Some options for doing this better include:
- code generation per type
- changing out the atlas entry for KV and giving each instance of the `Node` its own atlas.
- give the `CborIpldStore` hack its own atlas
- Convince rob and russ and friends that maybe generics would be okay? (i'd even be down with having a special file type for generics, so the compiler doesnt have to think very hard)
- use lazy decoding of the structures

cc @Stebalien @warpfork @dignifiedquire

**Comment by dignifiedquire** [comment]
I think given golangs constraints today, exploring code generation seems to be the best way really. I would imagine it being an optional addition, where you get `interface{}` out of the box, but then have an easy way to run some codegen to get the code you need.

In the long run I would like to encourage the golang team to add generics in some form, and help push that forward, but that's going to take time we likely don't have right now.

**Comment by Stebalien** [comment]
I'd:

1. Go with lazy decoding, if we can (we'll probably have to add a feature to refmt for this). I'm thinking something like RawJSON.
2. Change, e.g., the `Find` method signature to `Find(ctx, name, &value)` (like `Unmarshal`).
3. Allow users to wrap the hamt in their own custom type (or do codegen).

While I don't mind codegen, I'd just like to keep the amount of code we generate to a minimum.

**Comment by anorth** [comment]
@Stebalien would you consider this old issue to be more or less "done" now, with cbor-gen and deferred?

**Comment by Stebalien** [comment]
Eh, done enough for now.
