### ISSUE TITLE
go-ipld-cbor dependency unavailable

### ISSUE THREAD

**Issue by ghost** [filecoin-project/go-hamt-ipld#18]
Same issue as ipfs/go-car#5 - the go-ipld-cbor package referenced here (1.4.9 QmeyKxwBJgB7AP1DgoMAbqHajMnt4C6TuubsKBRVGZVFuH) isn't available.

Additionally the latest version in https://github.com/ipfs/go-ipld-cbor is only 1.3.0.

@whyrusleeping you did that update: https://github.com/ipfs/go-hamt-ipld/commit/343485da1096659a8a29f585c3fd03cdf45d135f

**Comment by Stebalien** [comment]
This library depended on the refmt branch of go-ipld-cbor. That has now been merged into master but we still need to cut a release.

**Comment by Stebalien** [comment]
I've cut a release of go-ipld-cbor but we need to bubble a few other updates for this to work.

**Comment by dignifiedquire** [comment]
for reference those versions are available here: https://github.com/filecoin-project/go-ipld-cbor (at least 1.4.8)

**Comment by anorth** [comment]
Closing as ancient history.
