### ISSUE TITLE
document the algorithm here in a spec

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-hamt-ipld#21]
This code should get a spec document describing how it works. Someone should be able to read the spec doc and produce a compatible library without having to look at this codebase.

**Comment by ianopolous** [comment]
When I implemented this in Java, these descriptions were very useful for initial understanding:
https://michael.steindorfer.name/publications/oopsla15.pdf
https://blog.acolyer.org/2015/11/27/hamt/
and then the Go code here completed the picture, (especially the critical difference from the papers of the batching in threes). 


My implementation:
https://github.com/Peergos/Peergos/blob/master/src/peergos/shared/hamt/Champ.java

**Comment by anorth** [comment]
There is now a lot more documentation, including of the algorithm, in the code.
