### ISSUE TITLE
Review Request

### ISSUE THREAD

**Issue by whyrusleeping** [filecoin-project/go-hamt-ipld#22]
I would like to solicit some review on this codebase and algorithm.

In particular, I would like help looking for:
- Points of potential non-determinism
- Scenarios where two HAMTs with the exact same keys and values would result in a different root hash.
- Scenarios where a value may end up being much deeper in the tree than it should be (say the tree has only four elements, and one of them is four levels deep)
- Edge cases where unanticipated issues or undefined behavior might happen
- Is there anything here that would make this a bad data structure to use for a blockchain state tree?

**Comment by ianopolous** [comment]
I've done some fuzzing of a generalized version of this algorithm (configurable bitwidth, max collisions and hash function), specifically focussing on determinism, and didn't find any problems. 

With a good hash function (not hash/fnv) there shouldn't be any problems with unnecessarily deep trees.

**Comment by whyrusleeping** [comment]
@ianopolous are there any 'fast' hash functions you would recommend? this impl is currently using murmur3, which I think should be pretty good.

**Comment by ianopolous** [comment]
I'm not a hash function expert but murmur3 is about 15x faster than SHA256 and you don't need a cryptographic hash function here anyway. I tried to find issues with murmur3 here when I switched it in, but I couldn't find any.

**Comment by ianopolous** [comment]
I expect this implementation also suffers from this issue?:
https://github.com/Peergos/Peergos/issues/421
