### ISSUE TITLE
Proposal to move this repo to filecoin-project org

### ISSUE THREAD

**Issue by rvagg** [filecoin-project/go-hamt-ipld#51]
This came up in some discussions elsewhere so I'm flagging it here for public discussion.

This HAMT implementation is very Filecoin specific and should probably not be confused as a generic IPFS or IPLD workhorse. Although the implementation is a useful reference and will likely be useful to some outside of Filecoin, it should be made clear that the evolution of this library will follow Filecoin's needs and may reject change proposals out of scope for Filecoin.

There will be another HAMT on offer by IPLD in Go to match the one we have [a spec for](https://github.com/ipld/specs/blob/master/data-structures/hashmap.md) (and an existing implementation in JavaScript) and that will offer some more flexibility and safety for variability of parameters that this implementation probably won't. And it'll build on top of the magical new go-ipld-prime work too so will have all sorts of in-built super-powers.

/cc @anorth @momack2

**Comment by anorth** [comment]
Yes please.

**Comment by momack2** [comment]
Fine with the concept - curious if that creates any problems on the IPFS side since AFAIK this may be used somewhere (@aschmahmann and @Stebalien would know)

**Comment by Stebalien** [comment]
go-ipfs doesn't use this. We use the one built-in to go-unixfs. When unixfsv2 ships..., I assume we'll get yet another hamp.

I.e., move it!
