### ISSUE TITLE
Redundant reads and writes

### ISSUE THREAD

**Issue by austinabell** [filecoin-project/go-hamt-ipld#68]
The issue is around the fact that a shard is persisted when a hamt is expanded [here](https://github.com/filecoin-project/go-hamt-ipld/blob/ae1417626c9b127890c94b7b3f5e5400268f217c/hamt.go#L684) and also the [cache is flushed and cleared even on read only access](https://github.com/filecoin-project/go-hamt-ipld/blob/ae1417626c9b127890c94b7b3f5e5400268f217c/hamt.go#L454) which leads to completely unnecessary writes.

I'll link to the PR where I add these extra writes/cache clears as I think it might be the easiest way to describe the diff and what can be improved: https://github.com/ChainSafe/forest/pull/731. The functionality that matches this repo currently is under the `go-interop` feature and can ignore the Amt changes (I grouped this change together)

I haven't benchmarked the difference in a real use case, but generally saw the writes and reads to be between 1.5-2x more than they need to be.

**Comment by rvagg** [comment]
Eric did some further investigation and documentation work on this here too: https://github.com/filecoin-project/go-hamt-ipld/pull/61

**Comment by Stebalien** [comment]
This will be fixed in #74.
