### ISSUE TITLE
All cached nodes are put in blockstore and removed after flush

### ISSUE THREAD

**Issue by austinabell** [filecoin-project/go-hamt-ipld#73]
First main issue with this is that a node that is cached during a read will be rewritten back into the store, even if not modified. https://github.com/filecoin-project/go-hamt-ipld/blob/699d2e0f5cc4f0f61bd35d3b7106ea687ec1e0c5/hamt.go#L455. This leads to a lot of extra unnecessary writes.

Second part to this is that all caches are dropped on flush, when it can be kept as a read cache https://github.com/filecoin-project/go-hamt-ipld/blob/699d2e0f5cc4f0f61bd35d3b7106ea687ec1e0c5/hamt.go#L464

This issue can maybe be summarized by indicating a need for managing a read and write cache, since they should be handled differently, as read caches shouldn't be removed/flushed, and write caches can be moved to read cache after flushing

**Comment by Stebalien** [comment]
This will be fixed in #74.
