### ISSUE TITLE
Implement logic for diffing two HAMTs

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-hamt-ipld#88]
As of https://github.com/filecoin-project/go-amt-ipld/pull/48 the AMT library supports diffing between two different AMTs. Efficient diffing of IPLD data structures is required by tools like [Visor](github.com/filecoin-projet/sentinel-visor) to extract blockchain state while keeping up with chain growth.

I am proposing that we add similar diffing support to the HAMT. Ideally, the diffing implementation will support HAMTs with different bit widths, but this constraint can be relaxed if it proves to be impracticable.

cc @iand

**Comment by ianopolous** [comment]
+1

There's an efficient ipld diff implementation in the IPFS pin update code (we use this heavily in Peergos, so I heavily optimised it years ago). 

In addition to this we've found a HAMT specific diff as suggested very useful - which gives you the new/changed/removed key+value mappings.

**Comment by frrist** [comment]
@ianopolous v3.1.0 has been released with support for HAMT diffing as described here.
